# Generated by Django 3.2.15 on 2022-09-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificadorURL', models.TextField()),
                ('nome', models.TextField()),
                ('categorias', models.TextField()),
                ('preco', models.TextField()),
                ('precoPromocional', models.TextField()),
                ('peso', models.TextField()),
                ('altura', models.TextField()),
                ('largura', models.TextField()),
                ('comprimento', models.TextField()),
                ('estoque', models.TextField()),
                ('SKU', models.TextField()),
                ('codigoDeBarras', models.TextField()),
                ('exibirNaLoja', models.TextField()),
                ('freteGratis', models.TextField()),
                ('descricao', models.TextField()),
                ('tags', models.TextField()),
                ('tituloParaSEO', models.TextField()),
                ('descricaoParaSEO', models.TextField()),
                ('marca', models.TextField()),
                ('produtoFisico', models.TextField()),
                ('MPN', models.TextField()),
                ('sexo', models.TextField()),
                ('faixaEtaria', models.TextField()),
            ],
        ),
    ]
